version: '3.3'

services:
   db:
     image: mysql:5.7
     volumes:
       - db_volume:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: root
       MYSQL_DATABASE: assign1
       MYSQL_USER: user
       MYSQL_PASSWORD: user
     ports:
       - "3306:3306"

   phpmyadmin:
     depends_on:
       - db
     image: phpmyadmin/phpmyadmin
     ports:
       - "9999:80"
volumes:
    db_volume: {}
